import type { ReportId } from './report.constants.js';

export interface ReportCsvColumn {
  key: string;
  label: string;
}

export interface ReportSpec {
  id: ReportId;
  defaultSort: string;
  sorts: Readonly<Record<string, string>>;
  dataSql: string;
  summarySql: string;
  tieBreaker: string;
  csvColumns: readonly ReportCsvColumn[];
  currency?: boolean;
}

const PARAMS = [
  'WITH params AS (',
  '  SELECT',
  '    $1::uuid AS warehouse_id,',
  '    $2::text AS movement_type,',
  '    $3::timestamptz AS date_from,',
  '    $4::timestamptz AS date_to,',
  '    $5::text AS search_pattern',
  ')',
].join('\n');

function query(lines: string[]): string {
  return [PARAMS, ...lines].join('\n');
}

const INVENTORY_BALANCE_DATA = query([
  'SELECT',
  '  ii."id"::text AS "id",',
  '  p."sku" AS "sku",',
  '  p."name" AS "productName",',
  '  w."name" AS "warehouseName",',
  '  ii."quantity_on_hand"::float8 AS "quantityOnHand",',
  '  ii."quantity_reserved"::float8 AS "quantityReserved",',
  '  (ii."quantity_on_hand" - ii."quantity_reserved")::float8 AS "quantityAvailable",',
  '  p."reorder_point"::float8 AS "reorderLevel"',
  'FROM "inventory_items" ii',
  'INNER JOIN "products" p ON p."id" = ii."product_id"',
  'INNER JOIN "warehouses" w ON w."id" = ii."warehouse_id"',
  'CROSS JOIN params',
  'WHERE (params.warehouse_id IS NULL OR ii."warehouse_id" = params.warehouse_id)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR p."sku" ILIKE params.search_pattern',
  '    OR p."name" ILIKE params.search_pattern',
  '  )',
]);

const INVENTORY_BALANCE_SUMMARY = query([
  'SELECT',
  '  COUNT(*)::integer AS "totalItems",',
  '  COUNT(DISTINCT ii."product_id")::integer AS "skuCount",',
  '  COALESCE(SUM(ii."quantity_on_hand"), 0)::float8 AS "totalOnHand",',
  '  COALESCE(SUM(ii."quantity_reserved"), 0)::float8 AS "totalReserved",',
  '  COALESCE(SUM(ii."quantity_on_hand" - ii."quantity_reserved"), 0)::float8 AS "totalAvailable"',
  'FROM "inventory_items" ii',
  'INNER JOIN "products" p ON p."id" = ii."product_id"',
  'CROSS JOIN params',
  'WHERE (params.warehouse_id IS NULL OR ii."warehouse_id" = params.warehouse_id)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR p."sku" ILIKE params.search_pattern',
  '    OR p."name" ILIKE params.search_pattern',
  '  )',
]);

const INVENTORY_VALUATION_DATA = query([
  'SELECT',
  '  ii."id"::text AS "id",',
  '  p."sku" AS "sku",',
  '  p."name" AS "productName",',
  '  w."name" AS "warehouseName",',
  '  ii."quantity_on_hand"::float8 AS "quantityOnHand",',
  '  ii."average_cost"::float8 AS "unitCost",',
  '  (ii."quantity_on_hand" * ii."average_cost")::float8 AS "inventoryValue"',
  'FROM "inventory_items" ii',
  'INNER JOIN "products" p ON p."id" = ii."product_id"',
  'INNER JOIN "warehouses" w ON w."id" = ii."warehouse_id"',
  'CROSS JOIN params',
  'WHERE (params.warehouse_id IS NULL OR ii."warehouse_id" = params.warehouse_id)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR p."sku" ILIKE params.search_pattern',
  '    OR p."name" ILIKE params.search_pattern',
  '  )',
]);

const INVENTORY_VALUATION_SUMMARY = query([
  'SELECT',
  '  COUNT(*)::integer AS "totalItems",',
  '  COUNT(DISTINCT ii."product_id")::integer AS "skuCount",',
  '  COALESCE(SUM(ii."quantity_on_hand"), 0)::float8 AS "totalQuantity",',
  '  COALESCE(SUM(ii."quantity_on_hand" * ii."average_cost"), 0)::float8 AS "totalValue"',
  'FROM "inventory_items" ii',
  'INNER JOIN "products" p ON p."id" = ii."product_id"',
  'CROSS JOIN params',
  'WHERE (params.warehouse_id IS NULL OR ii."warehouse_id" = params.warehouse_id)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR p."sku" ILIKE params.search_pattern',
  '    OR p."name" ILIKE params.search_pattern',
  '  )',
]);

const STOCK_MOVEMENTS_DATA = query([
  'SELECT',
  '  m."id"::text AS "id",',
  '  m."occurred_at" AS "occurredAt",',
  '  LOWER(REPLACE(m."type"::text, \'_\', \'-\')) AS "type",',
  '  p."sku" AS "sku",',
  '  p."name" AS "productName",',
  '  w."name" AS "warehouseName",',
  '  m."quantity_change"::float8 AS "quantityChange",',
  '  m."balance_after"::float8 AS "balanceAfter",',
  '  m."reference_number" AS "referenceNumber"',
  'FROM "stock_movements" m',
  'INNER JOIN "products" p ON p."id" = m."product_id"',
  'INNER JOIN "warehouses" w ON w."id" = m."warehouse_id"',
  'CROSS JOIN params',
  'WHERE (params.warehouse_id IS NULL OR m."warehouse_id" = params.warehouse_id)',
  '  AND (params.movement_type IS NULL OR m."type"::text = params.movement_type)',
  '  AND (params.date_from IS NULL OR m."occurred_at" >= params.date_from)',
  '  AND (params.date_to IS NULL OR m."occurred_at" < params.date_to)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR p."sku" ILIKE params.search_pattern',
  '    OR p."name" ILIKE params.search_pattern',
  '    OR COALESCE(m."reference_number", \'\') ILIKE params.search_pattern',
  '  )',
]);

const STOCK_MOVEMENTS_SUMMARY = query([
  'SELECT',
  '  COUNT(*)::integer AS "totalItems",',
  '  COUNT(*)::integer AS "movementCount",',
  '  COALESCE(SUM(m."quantity_change"), 0)::float8 AS "netQuantityChange"',
  'FROM "stock_movements" m',
  'INNER JOIN "products" p ON p."id" = m."product_id"',
  'CROSS JOIN params',
  'WHERE (params.warehouse_id IS NULL OR m."warehouse_id" = params.warehouse_id)',
  '  AND (params.movement_type IS NULL OR m."type"::text = params.movement_type)',
  '  AND (params.date_from IS NULL OR m."occurred_at" >= params.date_from)',
  '  AND (params.date_to IS NULL OR m."occurred_at" < params.date_to)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR p."sku" ILIKE params.search_pattern',
  '    OR p."name" ILIKE params.search_pattern',
  '    OR COALESCE(m."reference_number", \'\') ILIKE params.search_pattern',
  '  )',
]);

const LOW_STOCK_DATA = query([
  'SELECT',
  '  ii."id"::text AS "id",',
  '  p."sku" AS "sku",',
  '  p."name" AS "productName",',
  '  w."name" AS "warehouseName",',
  '  (ii."quantity_on_hand" - ii."quantity_reserved")::float8 AS "quantityAvailable",',
  '  p."reorder_point"::float8 AS "reorderLevel",',
  '  (p."reorder_point" - (ii."quantity_on_hand" - ii."quantity_reserved"))::float8 AS "shortageQuantity"',
  'FROM "inventory_items" ii',
  'INNER JOIN "products" p ON p."id" = ii."product_id"',
  'INNER JOIN "warehouses" w ON w."id" = ii."warehouse_id"',
  'CROSS JOIN params',
  'WHERE (ii."quantity_on_hand" - ii."quantity_reserved") > 0',
  '  AND (ii."quantity_on_hand" - ii."quantity_reserved") <= p."reorder_point"',
  '  AND (params.warehouse_id IS NULL OR ii."warehouse_id" = params.warehouse_id)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR p."sku" ILIKE params.search_pattern',
  '    OR p."name" ILIKE params.search_pattern',
  '  )',
]);

const LOW_STOCK_SUMMARY = query([
  'SELECT',
  '  COUNT(*)::integer AS "totalItems",',
  '  COUNT(DISTINCT ii."product_id")::integer AS "skuCount",',
  '  COALESCE(SUM(p."reorder_point" - (ii."quantity_on_hand" - ii."quantity_reserved")), 0)::float8 AS "totalShortage"',
  'FROM "inventory_items" ii',
  'INNER JOIN "products" p ON p."id" = ii."product_id"',
  'CROSS JOIN params',
  'WHERE (ii."quantity_on_hand" - ii."quantity_reserved") > 0',
  '  AND (ii."quantity_on_hand" - ii."quantity_reserved") <= p."reorder_point"',
  '  AND (params.warehouse_id IS NULL OR ii."warehouse_id" = params.warehouse_id)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR p."sku" ILIKE params.search_pattern',
  '    OR p."name" ILIKE params.search_pattern',
  '  )',
]);

const OUT_OF_STOCK_DATA = query([
  'SELECT',
  '  ii."id"::text AS "id",',
  '  p."sku" AS "sku",',
  '  p."name" AS "productName",',
  '  w."name" AS "warehouseName",',
  '  ii."quantity_on_hand"::float8 AS "quantityOnHand",',
  '  ii."quantity_reserved"::float8 AS "quantityReserved",',
  '  (ii."quantity_on_hand" - ii."quantity_reserved")::float8 AS "quantityAvailable"',
  'FROM "inventory_items" ii',
  'INNER JOIN "products" p ON p."id" = ii."product_id"',
  'INNER JOIN "warehouses" w ON w."id" = ii."warehouse_id"',
  'CROSS JOIN params',
  'WHERE (ii."quantity_on_hand" - ii."quantity_reserved") <= 0',
  '  AND (params.warehouse_id IS NULL OR ii."warehouse_id" = params.warehouse_id)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR p."sku" ILIKE params.search_pattern',
  '    OR p."name" ILIKE params.search_pattern',
  '  )',
]);

const OUT_OF_STOCK_SUMMARY = query([
  'SELECT',
  '  COUNT(*)::integer AS "totalItems",',
  '  COUNT(DISTINCT ii."product_id")::integer AS "skuCount"',
  'FROM "inventory_items" ii',
  'INNER JOIN "products" p ON p."id" = ii."product_id"',
  'CROSS JOIN params',
  'WHERE (ii."quantity_on_hand" - ii."quantity_reserved") <= 0',
  '  AND (params.warehouse_id IS NULL OR ii."warehouse_id" = params.warehouse_id)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR p."sku" ILIKE params.search_pattern',
  '    OR p."name" ILIKE params.search_pattern',
  '  )',
]);

const ADJUSTMENTS_DATA = query([
  'SELECT',
  '  a."id"::text AS "id",',
  '  a."posted_at" AS "occurredAt",',
  '  a."number" AS "adjustmentNumber",',
  '  w."name" AS "warehouseName",',
  '  p."sku" AS "sku",',
  '  p."name" AS "productName",',
  '  LOWER(a."direction"::text) AS "direction",',
  '  (CASE WHEN a."direction" = \'INCREASE\' THEN a."quantity" ELSE -a."quantity" END)::float8 AS "quantityChange",',
  '  a."reason_code" AS "reason"',
  'FROM "inventory_adjustments" a',
  'INNER JOIN "products" p ON p."id" = a."product_id"',
  'INNER JOIN "warehouses" w ON w."id" = a."warehouse_id"',
  'CROSS JOIN params',
  'WHERE a."status" = \'POSTED\'',
  '  AND (params.warehouse_id IS NULL OR a."warehouse_id" = params.warehouse_id)',
  '  AND (params.date_from IS NULL OR a."posted_at" >= params.date_from)',
  '  AND (params.date_to IS NULL OR a."posted_at" < params.date_to)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR a."number" ILIKE params.search_pattern',
  '    OR p."sku" ILIKE params.search_pattern',
  '    OR p."name" ILIKE params.search_pattern',
  '    OR a."reason_code" ILIKE params.search_pattern',
  '    OR COALESCE(a."notes", \'\') ILIKE params.search_pattern',
  '  )',
]);

const ADJUSTMENTS_SUMMARY = query([
  'SELECT',
  '  COUNT(*)::integer AS "totalItems",',
  '  COUNT(*)::integer AS "adjustmentCount",',
  '  COALESCE(SUM(CASE WHEN a."direction" = \'INCREASE\' THEN a."quantity" ELSE -a."quantity" END), 0)::float8 AS "netQuantityChange"',
  'FROM "inventory_adjustments" a',
  'INNER JOIN "products" p ON p."id" = a."product_id"',
  'CROSS JOIN params',
  'WHERE a."status" = \'POSTED\'',
  '  AND (params.warehouse_id IS NULL OR a."warehouse_id" = params.warehouse_id)',
  '  AND (params.date_from IS NULL OR a."posted_at" >= params.date_from)',
  '  AND (params.date_to IS NULL OR a."posted_at" < params.date_to)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR a."number" ILIKE params.search_pattern',
  '    OR p."sku" ILIKE params.search_pattern',
  '    OR p."name" ILIKE params.search_pattern',
  '    OR a."reason_code" ILIKE params.search_pattern',
  '    OR COALESCE(a."notes", \'\') ILIKE params.search_pattern',
  '  )',
]);

const TRANSFERS_DATA = query([
  'SELECT',
  '  t."id"::text AS "id",',
  '  t."created_at" AS "createdAt",',
  '  t."number" AS "transferNumber",',
  '  sw."name" AS "sourceWarehouseName",',
  '  dw."name" AS "destinationWarehouseName",',
  '  LOWER(t."status"::text) AS "status",',
  '  COUNT(tl."id")::integer AS "lineCount"',
  'FROM "inventory_transfers" t',
  'INNER JOIN "warehouses" sw ON sw."id" = t."source_warehouse_id"',
  'INNER JOIN "warehouses" dw ON dw."id" = t."destination_warehouse_id"',
  'LEFT JOIN "inventory_transfer_lines" tl ON tl."transfer_id" = t."id"',
  'LEFT JOIN "products" p ON p."id" = tl."product_id"',
  'CROSS JOIN params',
  'WHERE (params.warehouse_id IS NULL OR t."source_warehouse_id" = params.warehouse_id OR t."destination_warehouse_id" = params.warehouse_id)',
  '  AND (params.date_from IS NULL OR t."created_at" >= params.date_from)',
  '  AND (params.date_to IS NULL OR t."created_at" < params.date_to)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR t."number" ILIKE params.search_pattern',
  '    OR sw."name" ILIKE params.search_pattern',
  '    OR dw."name" ILIKE params.search_pattern',
  '    OR EXISTS (',
  '      SELECT 1',
  '      FROM "inventory_transfer_lines" sx',
  '      INNER JOIN "products" sp ON sp."id" = sx."product_id"',
  '      WHERE sx."transfer_id" = t."id"',
  '        AND (sp."sku" ILIKE params.search_pattern OR sp."name" ILIKE params.search_pattern)',
  '    )',
  '  )',
  'GROUP BY t."id", sw."name", dw."name"',
]);

const TRANSFERS_SUMMARY = query([
  'SELECT',
  '  COUNT(*)::integer AS "totalItems",',
  '  COUNT(*)::integer AS "transferCount",',
  '  COALESCE(SUM(x."lineCount"), 0)::integer AS "lineCount"',
  'FROM (',
  '  SELECT',
  '    t."id",',
  '    COUNT(tl."id")::integer AS "lineCount"',
  '  FROM "inventory_transfers" t',
  '  INNER JOIN "warehouses" sw ON sw."id" = t."source_warehouse_id"',
  '  INNER JOIN "warehouses" dw ON dw."id" = t."destination_warehouse_id"',
  '  LEFT JOIN "inventory_transfer_lines" tl ON tl."transfer_id" = t."id"',
  '  CROSS JOIN params',
  '  WHERE (params.warehouse_id IS NULL OR t."source_warehouse_id" = params.warehouse_id OR t."destination_warehouse_id" = params.warehouse_id)',
  '    AND (params.date_from IS NULL OR t."created_at" >= params.date_from)',
  '    AND (params.date_to IS NULL OR t."created_at" < params.date_to)',
  '    AND (',
  '      params.search_pattern IS NULL',
  '      OR t."number" ILIKE params.search_pattern',
  '      OR sw."name" ILIKE params.search_pattern',
  '      OR dw."name" ILIKE params.search_pattern',
  '      OR EXISTS (',
  '        SELECT 1',
  '        FROM "inventory_transfer_lines" sx',
  '        INNER JOIN "products" sp ON sp."id" = sx."product_id"',
  '        WHERE sx."transfer_id" = t."id"',
  '          AND (sp."sku" ILIKE params.search_pattern OR sp."name" ILIKE params.search_pattern)',
  '      )',
  '    )',
  '  GROUP BY t."id"',
  ') x',
]);

const STOCK_COUNT_VARIANCE_DATA = query([
  'SELECT',
  '  scl."id"::text AS "id",',
  '  sc."posted_at" AS "postedAt",',
  '  sc."number" AS "countNumber",',
  '  w."name" AS "warehouseName",',
  '  p."sku" AS "sku",',
  '  p."name" AS "productName",',
  '  scl."expected_quantity"::float8 AS "expectedQuantity",',
  '  scl."counted_quantity"::float8 AS "countedQuantity",',
  '  scl."variance_quantity"::float8 AS "varianceQuantity"',
  'FROM "stock_count_lines" scl',
  'INNER JOIN "stock_counts" sc ON sc."id" = scl."stock_count_id"',
  'INNER JOIN "products" p ON p."id" = scl."product_id"',
  'INNER JOIN "warehouses" w ON w."id" = sc."warehouse_id"',
  'CROSS JOIN params',
  'WHERE sc."status" = \'POSTED\'',
  '  AND scl."variance_quantity" IS NOT NULL',
  '  AND scl."variance_quantity" <> 0',
  '  AND (params.warehouse_id IS NULL OR sc."warehouse_id" = params.warehouse_id)',
  '  AND (params.date_from IS NULL OR sc."posted_at" >= params.date_from)',
  '  AND (params.date_to IS NULL OR sc."posted_at" < params.date_to)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR sc."number" ILIKE params.search_pattern',
  '    OR p."sku" ILIKE params.search_pattern',
  '    OR p."name" ILIKE params.search_pattern',
  '  )',
]);

const STOCK_COUNT_VARIANCE_SUMMARY = query([
  'SELECT',
  '  COUNT(*)::integer AS "totalItems",',
  '  COUNT(DISTINCT sc."id")::integer AS "countSessionCount",',
  '  COUNT(*)::integer AS "varianceLineCount",',
  '  COALESCE(SUM(scl."variance_quantity"), 0)::float8 AS "netVariance"',
  'FROM "stock_count_lines" scl',
  'INNER JOIN "stock_counts" sc ON sc."id" = scl."stock_count_id"',
  'INNER JOIN "products" p ON p."id" = scl."product_id"',
  'CROSS JOIN params',
  'WHERE sc."status" = \'POSTED\'',
  '  AND scl."variance_quantity" IS NOT NULL',
  '  AND scl."variance_quantity" <> 0',
  '  AND (params.warehouse_id IS NULL OR sc."warehouse_id" = params.warehouse_id)',
  '  AND (params.date_from IS NULL OR sc."posted_at" >= params.date_from)',
  '  AND (params.date_to IS NULL OR sc."posted_at" < params.date_to)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR sc."number" ILIKE params.search_pattern',
  '    OR p."sku" ILIKE params.search_pattern',
  '    OR p."name" ILIKE params.search_pattern',
  '  )',
]);

const PURCHASE_HISTORY_DATA = query([
  'SELECT',
  '  po."id"::text AS "id",',
  '  TO_CHAR(po."order_date", \'YYYY-MM-DD\') AS "orderDate",',
  '  po."number" AS "purchaseOrderNumber",',
  '  s."name" AS "supplierName",',
  '  w."name" AS "warehouseName",',
  '  LOWER(REPLACE(po."status"::text, \'_\', \'-\')) AS "status",',
  '  COUNT(pol."id")::integer AS "lineCount",',
  '  po."subtotal"::float8 AS "subtotal"',
  'FROM "purchase_orders" po',
  'INNER JOIN "suppliers" s ON s."id" = po."supplier_id"',
  'INNER JOIN "warehouses" w ON w."id" = po."warehouse_id"',
  'LEFT JOIN "purchase_order_lines" pol ON pol."purchase_order_id" = po."id"',
  'CROSS JOIN params',
  'WHERE (params.warehouse_id IS NULL OR po."warehouse_id" = params.warehouse_id)',
  '  AND (params.date_from IS NULL OR po."order_date" >= params.date_from::date)',
  '  AND (params.date_to IS NULL OR po."order_date" < params.date_to::date)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR po."number" ILIKE params.search_pattern',
  '    OR s."name" ILIKE params.search_pattern',
  '    OR EXISTS (',
  '      SELECT 1',
  '      FROM "purchase_order_lines" sx',
  '      INNER JOIN "products" sp ON sp."id" = sx."product_id"',
  '      WHERE sx."purchase_order_id" = po."id"',
  '        AND (sp."sku" ILIKE params.search_pattern OR sp."name" ILIKE params.search_pattern)',
  '    )',
  '  )',
  'GROUP BY po."id", s."name", w."name"',
]);

const PURCHASE_HISTORY_SUMMARY = query([
  'SELECT',
  '  COUNT(*)::integer AS "totalItems",',
  '  COUNT(*)::integer AS "orderCount",',
  '  COALESCE(SUM(po."subtotal") FILTER (WHERE po."status" <> \'CANCELLED\'), 0)::float8 AS "totalPurchased"',
  'FROM "purchase_orders" po',
  'INNER JOIN "suppliers" s ON s."id" = po."supplier_id"',
  'CROSS JOIN params',
  'WHERE (params.warehouse_id IS NULL OR po."warehouse_id" = params.warehouse_id)',
  '  AND (params.date_from IS NULL OR po."order_date" >= params.date_from::date)',
  '  AND (params.date_to IS NULL OR po."order_date" < params.date_to::date)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR po."number" ILIKE params.search_pattern',
  '    OR s."name" ILIKE params.search_pattern',
  '    OR EXISTS (',
  '      SELECT 1',
  '      FROM "purchase_order_lines" sx',
  '      INNER JOIN "products" sp ON sp."id" = sx."product_id"',
  '      WHERE sx."purchase_order_id" = po."id"',
  '        AND (sp."sku" ILIKE params.search_pattern OR sp."name" ILIKE params.search_pattern)',
  '    )',
  '  )',
]);

const RECEIVING_DATA = query([
  'SELECT',
  '  gr."id"::text AS "id",',
  '  TO_CHAR(gr."receipt_date", \'YYYY-MM-DD\') AS "receiptDate",',
  '  gr."number" AS "receiptNumber",',
  '  po."number" AS "purchaseOrderNumber",',
  '  s."name" AS "supplierName",',
  '  w."name" AS "warehouseName",',
  '  COUNT(grl."id")::integer AS "lineCount",',
  '  LOWER(gr."status"::text) AS "status"',
  'FROM "goods_receipts" gr',
  'INNER JOIN "purchase_orders" po ON po."id" = gr."purchase_order_id"',
  'INNER JOIN "suppliers" s ON s."id" = po."supplier_id"',
  'INNER JOIN "warehouses" w ON w."id" = po."warehouse_id"',
  'LEFT JOIN "goods_receipt_lines" grl ON grl."goods_receipt_id" = gr."id"',
  'CROSS JOIN params',
  'WHERE gr."status" = \'POSTED\'',
  '  AND (params.warehouse_id IS NULL OR po."warehouse_id" = params.warehouse_id)',
  '  AND (params.date_from IS NULL OR gr."receipt_date" >= params.date_from::date)',
  '  AND (params.date_to IS NULL OR gr."receipt_date" < params.date_to::date)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR gr."number" ILIKE params.search_pattern',
  '    OR po."number" ILIKE params.search_pattern',
  '    OR s."name" ILIKE params.search_pattern',
  '    OR COALESCE(gr."supplier_delivery_reference", \'\') ILIKE params.search_pattern',
  '  )',
  'GROUP BY gr."id", po."number", s."name", w."name"',
]);

const RECEIVING_SUMMARY = query([
  'SELECT',
  '  COUNT(DISTINCT gr."id")::integer AS "totalItems",',
  '  COUNT(DISTINCT gr."id")::integer AS "receiptCount",',
  '  COUNT(grl."id")::integer AS "receivedLineCount",',
  '  COALESCE(SUM(grl."quantity_received"), 0)::float8 AS "receivedQuantity"',
  'FROM "goods_receipts" gr',
  'INNER JOIN "purchase_orders" po ON po."id" = gr."purchase_order_id"',
  'INNER JOIN "suppliers" s ON s."id" = po."supplier_id"',
  'LEFT JOIN "goods_receipt_lines" grl ON grl."goods_receipt_id" = gr."id"',
  'CROSS JOIN params',
  'WHERE gr."status" = \'POSTED\'',
  '  AND (params.warehouse_id IS NULL OR po."warehouse_id" = params.warehouse_id)',
  '  AND (params.date_from IS NULL OR gr."receipt_date" >= params.date_from::date)',
  '  AND (params.date_to IS NULL OR gr."receipt_date" < params.date_to::date)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR gr."number" ILIKE params.search_pattern',
  '    OR po."number" ILIKE params.search_pattern',
  '    OR s."name" ILIKE params.search_pattern',
  '    OR COALESCE(gr."supplier_delivery_reference", \'\') ILIKE params.search_pattern',
  '  )',
]);

const SUPPLIER_PURCHASES_DATA = query([
  'SELECT',
  '  s."id"::text AS "id",',
  '  s."code" AS "supplierCode",',
  '  s."name" AS "supplierName",',
  '  COUNT(po."id")::integer AS "orderCount",',
  '  COUNT(po."id") FILTER (WHERE po."status" = \'RECEIVED\')::integer AS "receivedOrderCount",',
  '  COALESCE(SUM(po."subtotal") FILTER (WHERE po."status" <> \'CANCELLED\'), 0)::float8 AS "totalPurchased"',
  'FROM "purchase_orders" po',
  'INNER JOIN "suppliers" s ON s."id" = po."supplier_id"',
  'CROSS JOIN params',
  'WHERE (params.warehouse_id IS NULL OR po."warehouse_id" = params.warehouse_id)',
  '  AND (params.date_from IS NULL OR po."order_date" >= params.date_from::date)',
  '  AND (params.date_to IS NULL OR po."order_date" < params.date_to::date)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR s."code" ILIKE params.search_pattern',
  '    OR s."name" ILIKE params.search_pattern',
  '  )',
  'GROUP BY s."id"',
]);

const SUPPLIER_PURCHASES_SUMMARY = query([
  'SELECT',
  '  COUNT(*)::integer AS "totalItems",',
  '  COUNT(*)::integer AS "supplierCount",',
  '  COALESCE(SUM(x."orderCount"), 0)::integer AS "orderCount",',
  '  COALESCE(SUM(x."totalPurchased"), 0)::float8 AS "totalPurchased"',
  'FROM (',
  '  SELECT',
  '    s."id",',
  '    COUNT(po."id")::integer AS "orderCount",',
  '    COALESCE(SUM(po."subtotal") FILTER (WHERE po."status" <> \'CANCELLED\'), 0) AS "totalPurchased"',
  '  FROM "purchase_orders" po',
  '  INNER JOIN "suppliers" s ON s."id" = po."supplier_id"',
  '  CROSS JOIN params',
  '  WHERE (params.warehouse_id IS NULL OR po."warehouse_id" = params.warehouse_id)',
  '    AND (params.date_from IS NULL OR po."order_date" >= params.date_from::date)',
  '    AND (params.date_to IS NULL OR po."order_date" < params.date_to::date)',
  '    AND (',
  '      params.search_pattern IS NULL',
  '      OR s."code" ILIKE params.search_pattern',
  '      OR s."name" ILIKE params.search_pattern',
  '    )',
  '  GROUP BY s."id"',
  ') x',
]);

const SALES_ORDERS_DATA = query([
  'SELECT',
  '  so."id"::text AS "id",',
  '  TO_CHAR(so."order_date", \'YYYY-MM-DD\') AS "orderDate",',
  '  so."number" AS "salesOrderNumber",',
  '  c."name" AS "customerName",',
  '  w."name" AS "warehouseName",',
  '  LOWER(so."status"::text) AS "status",',
  '  COUNT(sol."id")::integer AS "lineCount",',
  '  so."subtotal"::float8 AS "subtotal"',
  'FROM "sales_orders" so',
  'INNER JOIN "customers" c ON c."id" = so."customer_id"',
  'INNER JOIN "warehouses" w ON w."id" = so."warehouse_id"',
  'LEFT JOIN "sales_order_lines" sol ON sol."sales_order_id" = so."id"',
  'CROSS JOIN params',
  'WHERE (params.warehouse_id IS NULL OR so."warehouse_id" = params.warehouse_id)',
  '  AND (params.date_from IS NULL OR so."order_date" >= params.date_from::date)',
  '  AND (params.date_to IS NULL OR so."order_date" < params.date_to::date)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR so."number" ILIKE params.search_pattern',
  '    OR c."name" ILIKE params.search_pattern',
  '    OR EXISTS (',
  '      SELECT 1',
  '      FROM "sales_order_lines" sx',
  '      INNER JOIN "products" sp ON sp."id" = sx."product_id"',
  '      WHERE sx."sales_order_id" = so."id"',
  '        AND (sp."sku" ILIKE params.search_pattern OR sp."name" ILIKE params.search_pattern)',
  '    )',
  '  )',
  'GROUP BY so."id", c."name", w."name"',
]);

const SALES_ORDERS_SUMMARY = query([
  'SELECT',
  '  COUNT(*)::integer AS "totalItems",',
  '  COUNT(*)::integer AS "orderCount",',
  '  COUNT(*) FILTER (WHERE so."status" IN (\'DISPATCHED\', \'COMPLETED\'))::integer AS "dispatchedCount",',
  '  COALESCE(SUM(so."subtotal") FILTER (WHERE so."status" <> \'CANCELLED\'), 0)::float8 AS "totalSalesValue"',
  'FROM "sales_orders" so',
  'INNER JOIN "customers" c ON c."id" = so."customer_id"',
  'CROSS JOIN params',
  'WHERE (params.warehouse_id IS NULL OR so."warehouse_id" = params.warehouse_id)',
  '  AND (params.date_from IS NULL OR so."order_date" >= params.date_from::date)',
  '  AND (params.date_to IS NULL OR so."order_date" < params.date_to::date)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR so."number" ILIKE params.search_pattern',
  '    OR c."name" ILIKE params.search_pattern',
  '    OR EXISTS (',
  '      SELECT 1',
  '      FROM "sales_order_lines" sx',
  '      INNER JOIN "products" sp ON sp."id" = sx."product_id"',
  '      WHERE sx."sales_order_id" = so."id"',
  '        AND (sp."sku" ILIKE params.search_pattern OR sp."name" ILIKE params.search_pattern)',
  '    )',
  '  )',
]);

const SALES_RETURNS_DATA = query([
  'SELECT',
  '  sr."id"::text AS "id",',
  '  sr."created_at" AS "createdAt",',
  '  sr."number" AS "returnNumber",',
  '  so."number" AS "salesOrderNumber",',
  '  c."name" AS "customerName",',
  '  w."name" AS "warehouseName",',
  '  COUNT(srl."id")::integer AS "lineCount",',
  '  COALESCE(SUM(srl."quantity_returned"), 0)::float8 AS "quantityReturned"',
  'FROM "sales_returns" sr',
  'INNER JOIN "sales_orders" so ON so."id" = sr."sales_order_id"',
  'INNER JOIN "customers" c ON c."id" = so."customer_id"',
  'INNER JOIN "warehouses" w ON w."id" = so."warehouse_id"',
  'LEFT JOIN "sales_return_lines" srl ON srl."sales_return_id" = sr."id"',
  'CROSS JOIN params',
  'WHERE (params.warehouse_id IS NULL OR so."warehouse_id" = params.warehouse_id)',
  '  AND (params.date_from IS NULL OR sr."created_at" >= params.date_from)',
  '  AND (params.date_to IS NULL OR sr."created_at" < params.date_to)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR sr."number" ILIKE params.search_pattern',
  '    OR so."number" ILIKE params.search_pattern',
  '    OR c."name" ILIKE params.search_pattern',
  '    OR EXISTS (',
  '      SELECT 1',
  '      FROM "sales_return_lines" sx',
  '      INNER JOIN "sales_order_lines" sol ON sol."id" = sx."sales_order_line_id"',
  '      INNER JOIN "products" sp ON sp."id" = sol."product_id"',
  '      WHERE sx."sales_return_id" = sr."id"',
  '        AND (sp."sku" ILIKE params.search_pattern OR sp."name" ILIKE params.search_pattern)',
  '    )',
  '  )',
  'GROUP BY sr."id", so."number", c."name", w."name"',
]);

const SALES_RETURNS_SUMMARY = query([
  'SELECT',
  '  COUNT(DISTINCT sr."id")::integer AS "totalItems",',
  '  COUNT(DISTINCT sr."id")::integer AS "returnCount",',
  '  COUNT(srl."id")::integer AS "lineCount",',
  '  COALESCE(SUM(srl."quantity_returned"), 0)::float8 AS "quantityReturned"',
  'FROM "sales_returns" sr',
  'INNER JOIN "sales_orders" so ON so."id" = sr."sales_order_id"',
  'INNER JOIN "customers" c ON c."id" = so."customer_id"',
  'LEFT JOIN "sales_return_lines" srl ON srl."sales_return_id" = sr."id"',
  'CROSS JOIN params',
  'WHERE (params.warehouse_id IS NULL OR so."warehouse_id" = params.warehouse_id)',
  '  AND (params.date_from IS NULL OR sr."created_at" >= params.date_from)',
  '  AND (params.date_to IS NULL OR sr."created_at" < params.date_to)',
  '  AND (',
  '    params.search_pattern IS NULL',
  '    OR sr."number" ILIKE params.search_pattern',
  '    OR so."number" ILIKE params.search_pattern',
  '    OR c."name" ILIKE params.search_pattern',
  '    OR EXISTS (',
  '      SELECT 1',
  '      FROM "sales_return_lines" sx',
  '      INNER JOIN "sales_order_lines" sol ON sol."id" = sx."sales_order_line_id"',
  '      INNER JOIN "products" sp ON sp."id" = sol."product_id"',
  '      WHERE sx."sales_return_id" = sr."id"',
  '        AND (sp."sku" ILIKE params.search_pattern OR sp."name" ILIKE params.search_pattern)',
  '    )',
  '  )',
]);

const commonInventorySorts = {
  productName: '"productName"',
  sku: '"sku"',
  warehouseName: '"warehouseName"',
} as const;

export const REPORT_SPECS: Readonly<Record<ReportId, ReportSpec>> = {
  'inventory-balance': {
    id: 'inventory-balance',
    defaultSort: 'productName',
    sorts: {
      ...commonInventorySorts,
      quantityOnHand: '"quantityOnHand"',
      quantityReserved: '"quantityReserved"',
      quantityAvailable: '"quantityAvailable"',
      reorderLevel: '"reorderLevel"',
    },
    dataSql: INVENTORY_BALANCE_DATA,
    summarySql: INVENTORY_BALANCE_SUMMARY,
    tieBreaker: '"id" ASC',
    csvColumns: [
      { key: 'sku', label: 'SKU' },
      { key: 'productName', label: 'Product' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'quantityOnHand', label: 'On hand' },
      { key: 'quantityReserved', label: 'Reserved' },
      { key: 'quantityAvailable', label: 'Available' },
      { key: 'reorderLevel', label: 'Reorder level' },
    ],
  },
  'inventory-valuation': {
    id: 'inventory-valuation',
    defaultSort: 'productName',
    sorts: {
      ...commonInventorySorts,
      quantityOnHand: '"quantityOnHand"',
      unitCost: '"unitCost"',
      inventoryValue: '"inventoryValue"',
    },
    dataSql: INVENTORY_VALUATION_DATA,
    summarySql: INVENTORY_VALUATION_SUMMARY,
    tieBreaker: '"id" ASC',
    currency: true,
    csvColumns: [
      { key: 'sku', label: 'SKU' },
      { key: 'productName', label: 'Product' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'quantityOnHand', label: 'On hand' },
      { key: 'unitCost', label: 'Unit cost' },
      { key: 'inventoryValue', label: 'Inventory value' },
    ],
  },
  'stock-movements': {
    id: 'stock-movements',
    defaultSort: 'occurredAt',
    sorts: {
      occurredAt: '"occurredAt"',
      type: '"type"',
      sku: '"sku"',
      productName: '"productName"',
      warehouseName: '"warehouseName"',
      quantityChange: '"quantityChange"',
      balanceAfter: '"balanceAfter"',
      referenceNumber: '"referenceNumber"',
    },
    dataSql: STOCK_MOVEMENTS_DATA,
    summarySql: STOCK_MOVEMENTS_SUMMARY,
    tieBreaker: '"id" ASC',
    csvColumns: [
      { key: 'occurredAt', label: 'Occurred' },
      { key: 'type', label: 'Type' },
      { key: 'sku', label: 'SKU' },
      { key: 'productName', label: 'Product' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'quantityChange', label: 'Quantity change' },
      { key: 'balanceAfter', label: 'Balance after' },
      { key: 'referenceNumber', label: 'Reference' },
    ],
  },
  'low-stock': {
    id: 'low-stock',
    defaultSort: 'shortageQuantity',
    sorts: {
      ...commonInventorySorts,
      quantityAvailable: '"quantityAvailable"',
      reorderLevel: '"reorderLevel"',
      shortageQuantity: '"shortageQuantity"',
    },
    dataSql: LOW_STOCK_DATA,
    summarySql: LOW_STOCK_SUMMARY,
    tieBreaker: '"id" ASC',
    csvColumns: [
      { key: 'sku', label: 'SKU' },
      { key: 'productName', label: 'Product' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'quantityAvailable', label: 'Available' },
      { key: 'reorderLevel', label: 'Reorder level' },
      { key: 'shortageQuantity', label: 'Shortage' },
    ],
  },
  'out-of-stock': {
    id: 'out-of-stock',
    defaultSort: 'productName',
    sorts: {
      ...commonInventorySorts,
      quantityOnHand: '"quantityOnHand"',
      quantityReserved: '"quantityReserved"',
      quantityAvailable: '"quantityAvailable"',
    },
    dataSql: OUT_OF_STOCK_DATA,
    summarySql: OUT_OF_STOCK_SUMMARY,
    tieBreaker: '"id" ASC',
    csvColumns: [
      { key: 'sku', label: 'SKU' },
      { key: 'productName', label: 'Product' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'quantityOnHand', label: 'On hand' },
      { key: 'quantityReserved', label: 'Reserved' },
      { key: 'quantityAvailable', label: 'Available' },
    ],
  },
  adjustments: {
    id: 'adjustments',
    defaultSort: 'occurredAt',
    sorts: {
      occurredAt: '"occurredAt"',
      adjustmentNumber: '"adjustmentNumber"',
      warehouseName: '"warehouseName"',
      sku: '"sku"',
      productName: '"productName"',
      direction: '"direction"',
      quantityChange: '"quantityChange"',
      reason: '"reason"',
    },
    dataSql: ADJUSTMENTS_DATA,
    summarySql: ADJUSTMENTS_SUMMARY,
    tieBreaker: '"id" ASC',
    csvColumns: [
      { key: 'occurredAt', label: 'Occurred' },
      { key: 'adjustmentNumber', label: 'Adjustment' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'sku', label: 'SKU' },
      { key: 'productName', label: 'Product' },
      { key: 'direction', label: 'Direction' },
      { key: 'quantityChange', label: 'Quantity change' },
      { key: 'reason', label: 'Reason' },
    ],
  },
  transfers: {
    id: 'transfers',
    defaultSort: 'createdAt',
    sorts: {
      createdAt: '"createdAt"',
      transferNumber: '"transferNumber"',
      sourceWarehouseName: '"sourceWarehouseName"',
      destinationWarehouseName: '"destinationWarehouseName"',
      status: '"status"',
      lineCount: '"lineCount"',
    },
    dataSql: TRANSFERS_DATA,
    summarySql: TRANSFERS_SUMMARY,
    tieBreaker: '"id" ASC',
    csvColumns: [
      { key: 'createdAt', label: 'Created' },
      { key: 'transferNumber', label: 'Transfer' },
      { key: 'sourceWarehouseName', label: 'Source warehouse' },
      { key: 'destinationWarehouseName', label: 'Destination warehouse' },
      { key: 'status', label: 'Status' },
      { key: 'lineCount', label: 'Lines' },
    ],
  },
  'stock-count-variance': {
    id: 'stock-count-variance',
    defaultSort: 'postedAt',
    sorts: {
      postedAt: '"postedAt"',
      countNumber: '"countNumber"',
      warehouseName: '"warehouseName"',
      sku: '"sku"',
      productName: '"productName"',
      expectedQuantity: '"expectedQuantity"',
      countedQuantity: '"countedQuantity"',
      varianceQuantity: '"varianceQuantity"',
    },
    dataSql: STOCK_COUNT_VARIANCE_DATA,
    summarySql: STOCK_COUNT_VARIANCE_SUMMARY,
    tieBreaker: '"id" ASC',
    csvColumns: [
      { key: 'postedAt', label: 'Posted' },
      { key: 'countNumber', label: 'Count' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'sku', label: 'SKU' },
      { key: 'productName', label: 'Product' },
      { key: 'expectedQuantity', label: 'Expected' },
      { key: 'countedQuantity', label: 'Counted' },
      { key: 'varianceQuantity', label: 'Variance' },
    ],
  },
  'purchase-history': {
    id: 'purchase-history',
    defaultSort: 'orderDate',
    sorts: {
      orderDate: '"orderDate"',
      purchaseOrderNumber: '"purchaseOrderNumber"',
      supplierName: '"supplierName"',
      warehouseName: '"warehouseName"',
      status: '"status"',
      lineCount: '"lineCount"',
      subtotal: '"subtotal"',
    },
    dataSql: PURCHASE_HISTORY_DATA,
    summarySql: PURCHASE_HISTORY_SUMMARY,
    tieBreaker: '"id" ASC',
    currency: true,
    csvColumns: [
      { key: 'orderDate', label: 'Order date' },
      { key: 'purchaseOrderNumber', label: 'Purchase order' },
      { key: 'supplierName', label: 'Supplier' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'status', label: 'Status' },
      { key: 'lineCount', label: 'Lines' },
      { key: 'subtotal', label: 'Subtotal' },
    ],
  },
  receiving: {
    id: 'receiving',
    defaultSort: 'receiptDate',
    sorts: {
      receiptDate: '"receiptDate"',
      receiptNumber: '"receiptNumber"',
      purchaseOrderNumber: '"purchaseOrderNumber"',
      supplierName: '"supplierName"',
      warehouseName: '"warehouseName"',
      lineCount: '"lineCount"',
      status: '"status"',
    },
    dataSql: RECEIVING_DATA,
    summarySql: RECEIVING_SUMMARY,
    tieBreaker: '"id" ASC',
    csvColumns: [
      { key: 'receiptDate', label: 'Receipt date' },
      { key: 'receiptNumber', label: 'Receipt' },
      { key: 'purchaseOrderNumber', label: 'Purchase order' },
      { key: 'supplierName', label: 'Supplier' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'lineCount', label: 'Lines' },
      { key: 'status', label: 'Status' },
    ],
  },
  'supplier-purchases': {
    id: 'supplier-purchases',
    defaultSort: 'totalPurchased',
    sorts: {
      supplierCode: '"supplierCode"',
      supplierName: '"supplierName"',
      orderCount: '"orderCount"',
      receivedOrderCount: '"receivedOrderCount"',
      totalPurchased: '"totalPurchased"',
    },
    dataSql: SUPPLIER_PURCHASES_DATA,
    summarySql: SUPPLIER_PURCHASES_SUMMARY,
    tieBreaker: '"id" ASC',
    currency: true,
    csvColumns: [
      { key: 'supplierCode', label: 'Supplier code' },
      { key: 'supplierName', label: 'Supplier' },
      { key: 'orderCount', label: 'Orders' },
      { key: 'receivedOrderCount', label: 'Received' },
      { key: 'totalPurchased', label: 'Purchased' },
    ],
  },
  'sales-orders': {
    id: 'sales-orders',
    defaultSort: 'orderDate',
    sorts: {
      orderDate: '"orderDate"',
      salesOrderNumber: '"salesOrderNumber"',
      customerName: '"customerName"',
      warehouseName: '"warehouseName"',
      status: '"status"',
      lineCount: '"lineCount"',
      subtotal: '"subtotal"',
    },
    dataSql: SALES_ORDERS_DATA,
    summarySql: SALES_ORDERS_SUMMARY,
    tieBreaker: '"id" ASC',
    currency: true,
    csvColumns: [
      { key: 'orderDate', label: 'Order date' },
      { key: 'salesOrderNumber', label: 'Sales order' },
      { key: 'customerName', label: 'Customer' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'status', label: 'Status' },
      { key: 'lineCount', label: 'Lines' },
      { key: 'subtotal', label: 'Subtotal' },
    ],
  },
  'sales-returns': {
    id: 'sales-returns',
    defaultSort: 'createdAt',
    sorts: {
      createdAt: '"createdAt"',
      returnNumber: '"returnNumber"',
      salesOrderNumber: '"salesOrderNumber"',
      customerName: '"customerName"',
      warehouseName: '"warehouseName"',
      lineCount: '"lineCount"',
      quantityReturned: '"quantityReturned"',
    },
    dataSql: SALES_RETURNS_DATA,
    summarySql: SALES_RETURNS_SUMMARY,
    tieBreaker: '"id" ASC',
    csvColumns: [
      { key: 'createdAt', label: 'Created' },
      { key: 'returnNumber', label: 'Return' },
      { key: 'salesOrderNumber', label: 'Sales order' },
      { key: 'customerName', label: 'Customer' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'lineCount', label: 'Lines' },
      { key: 'quantityReturned', label: 'Returned quantity' },
    ],
  },
};
